/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  type AnyPgColumn,
  numeric,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_account_status = pgEnum("enum_users_account_status", [
  "active",
  "warned",
  "suspended",
  "banned",
]);
export const enum_users_role = pgEnum("enum_users_role", [
  "buyer",
  "individual_seller",
  "dealer",
  "moderator",
  "admin",
]);
export const enum_users_requested_role = pgEnum("enum_users_requested_role", [
  "buyer",
  "individual_seller",
  "dealer",
]);
export const enum_dealers_deals_in = pgEnum("enum_dealers_deals_in", [
  "new",
  "import",
  "locally-used",
  "heavy-machinery",
]);
export const enum_dealers_county = pgEnum("enum_dealers_county", [
  "Nairobi",
  "Mombasa",
  "Kiambu",
  "Nakuru",
  "Uasin Gishu",
  "Kisumu",
  "Machakos",
  "Other",
]);
export const enum_dealers_verification_status = pgEnum(
  "enum_dealers_verification_status",
  ["unverified", "pending", "verified", "rejected"],
);
export const enum_dealers_subscription_tier = pgEnum(
  "enum_dealers_subscription_tier",
  ["free", "pro", "premium"],
);
export const enum_service_providers_services = pgEnum(
  "enum_service_providers_services",
  [
    "certified-mechanic",
    "auto-electrical",
    "body-painting",
    "tinting",
    "detailing",
    "identity-marking",
    "inspection",
    "spare-parts",
    "car-hire",
    "leasing",
    "towing",
  ],
);
export const enum_service_providers_verification_status = pgEnum(
  "enum_service_providers_verification_status",
  ["unverified", "pending", "verified", "rejected", "expired"],
);
export const enum_listings_category = pgEnum("enum_listings_category", [
  "car",
  "motorcycle",
  "tractor",
  "heavy-machinery",
  "pickup-van",
  "truck",
  "bus",
  "trailer",
  "tuk-tuk",
  "spare-parts",
]);
export const enum_listings_condition = pgEnum("enum_listings_condition", [
  "brand-new",
  "locally-assembled",
  "foreign-used",
  "locally-used",
]);
export const enum_listings_transmission = pgEnum("enum_listings_transmission", [
  "manual",
  "automatic",
  "cvt",
]);
export const enum_listings_fuel_type = pgEnum("enum_listings_fuel_type", [
  "petrol",
  "diesel",
  "hybrid",
  "electric",
]);
export const enum_listings_body_type = pgEnum("enum_listings_body_type", [
  "sedan",
  "suv",
  "hatchback",
  "wagon",
  "pickup",
  "van",
  "coupe",
  "convertible",
]);
export const enum_listings_heavy_machine_specs_equipment_type = pgEnum(
  "enum_listings_heavy_machine_specs_equipment_type",
  [
    "excavator",
    "bulldozer",
    "wheel-loader",
    "grader",
    "backhoe-loader",
    "tractor",
    "crane",
    "forklift",
    "compactor-/-roller",
    "combine-harvester",
    "cane-loader",
    "generator",
    "other",
  ],
);
export const enum_listings_spare_part_details_part_condition = pgEnum(
  "enum_listings_spare_part_details_part_condition",
  ["new", "refurbished", "used"],
);
export const enum_listings_duty_status = pgEnum("enum_listings_duty_status", [
  "duty-paid",
  "bonded-pre-clearance",
]);
export const enum_listings_currency = pgEnum("enum_listings_currency", ["KES"]);
export const enum_listings_county = pgEnum("enum_listings_county", [
  "Nairobi",
  "Mombasa",
  "Kiambu",
  "Nakuru",
  "Uasin Gishu",
  "Kisumu",
  "Machakos",
  "Kajiado",
  "Kilifi",
  "Meru",
  "Nyeri",
  "Other",
]);
export const enum_listings_status = pgEnum("enum_listings_status", [
  "draft",
  "pending-review",
  "active",
  "sold",
  "expired",
  "rejected",
]);
export const enum_listings_moderation_flag = pgEnum(
  "enum_listings_moderation_flag",
  ["none", "price-outlier-low", "duplicate-vin"],
);
export const enum_reviews_target_type = pgEnum("enum_reviews_target_type", [
  "dealer",
  "service-provider",
  "seller",
]);
export const enum_reviews_status = pgEnum("enum_reviews_status", [
  "pending",
  "published",
  "rejected",
]);
export const enum_reports_target_type = pgEnum("enum_reports_target_type", [
  "listing",
  "user",
  "dealer",
  "service-provider",
]);
export const enum_reports_reason = pgEnum("enum_reports_reason", [
  "suspected-fraud",
  "advance-fee-scam",
  "misleading-listing",
  "impersonation",
  "abuse",
  "other",
]);
export const enum_reports_status = pgEnum("enum_reports_status", [
  "open",
  "triaged",
  "under-review",
  "actioned",
  "resolved",
  "dismissed",
]);
export const enum_contact_messages_status = pgEnum(
  "enum_contact_messages_status",
  ["new", "in-progress", "resolved"],
);
export const enum_verification_documents_owner_type = pgEnum(
  "enum_verification_documents_owner_type",
  ["user", "dealer", "service-provider"],
);
export const enum_verification_documents_document_type = pgEnum(
  "enum_verification_documents_document_type",
  [
    "national-id",
    "business-permit",
    "kra-pin",
    "professional-certificate",
    "other",
  ],
);
export const enum_verification_documents_status = pgEnum(
  "enum_verification_documents_status",
  ["pending", "accepted", "rejected", "expired"],
);
export const enum_whatsapp_submissions_status = pgEnum(
  "enum_whatsapp_submissions_status",
  [
    "received",
    "needs-details",
    "claimed",
    "under-review",
    "approved",
    "rejected",
    "converted",
  ],
);
export const enum_whatsapp_submissions_onboarding_status = pgEnum(
  "enum_whatsapp_submissions_onboarding_status",
  ["unassigned", "assigned", "awaiting-dealer", "dealer-approved", "completed"],
);
export const enum_whatsapp_messages_direction = pgEnum(
  "enum_whatsapp_messages_direction",
  ["inbound", "outbound"],
);
export const enum_whatsapp_messages_status = pgEnum(
  "enum_whatsapp_messages_status",
  ["queued", "sent", "delivered", "read", "failed"],
);
export const enum_whatsapp_media_review_status = pgEnum(
  "enum_whatsapp_media_review_status",
  ["pending", "approved", "rejected"],
);
export const enum_featured_orders_plan = pgEnum("enum_featured_orders_plan", [
  "boost-3d",
  "boost-7d",
  "boost-30d",
  "homepage-spotlight-7d",
]);
export const enum_featured_orders_payment_provider = pgEnum(
  "enum_featured_orders_payment_provider",
  ["mpesa", "card"],
);
export const enum_featured_orders_status = pgEnum(
  "enum_featured_orders_status",
  ["pending", "paid", "failed", "expired"],
);
export const enum_inquiries_channel = pgEnum("enum_inquiries_channel", [
  "whatsapp",
  "phone",
  "form",
]);
export const enum_inspections_checklist_result = pgEnum(
  "enum_inspections_checklist_result",
  ["pass", "fail", "not-applicable"],
);
export const enum_inspections_status = pgEnum("enum_inspections_status", [
  "requested",
  "scheduled",
  "completed",
  "failed",
]);
export const enum_inspections_overall_result = pgEnum(
  "enum_inspections_overall_result",
  ["pass", "pass-with-notes", "fail"],
);
export const enum_crsp_schedule_fuel_type = pgEnum(
  "enum_crsp_schedule_fuel_type",
  ["petrol", "diesel", "hybrid", "electric"],
);
export const enum_crsp_schedule_category = pgEnum(
  "enum_crsp_schedule_category",
  [
    "car",
    "motorcycle",
    "tractor",
    "heavy-machinery",
    "pickup-van",
    "truck",
    "bus",
    "trailer",
    "tuk-tuk",
    "spare-parts",
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    publicSlug: varchar("public_slug"),
    bio: varchar("bio"),
    website: varchar("website"),
    county: varchar("county"),
    town: varchar("town"),
    accountStatus:
      enum_users_account_status("account_status").default("active"),
    suspensionEndsAt: timestamp("suspension_ends_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    moderationNote: varchar("moderation_note"),
    verificationExpiresAt: timestamp("verification_expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    phone: varchar("phone").notNull(),
    whatsappOptIn: boolean("whatsapp_opt_in").default(true),
    role: enum_users_role("role").notNull().default("buyer"),
    requestedRole: enum_users_requested_role("requested_role"),
    avatar: integer("avatar_id").references((): AnyPgColumn => media.id, {
      onDelete: "set null",
    }),
    idVerified: boolean("id_verified").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    _verified: boolean("_verified"),
    _verificationToken: varchar("_verificationtoken"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    uniqueIndex("users_public_slug_idx").on(columns.publicSlug),
    uniqueIndex("users_phone_idx").on(columns.phone),
    index("users_avatar_idx").on(columns.avatar),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const users_rels = pgTable(
  "users_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    listingsID: integer("listings_id"),
  },
  (columns) => [
    index("users_rels_order_idx").on(columns.order),
    index("users_rels_parent_idx").on(columns.parent),
    index("users_rels_path_idx").on(columns.path),
    index("users_rels_listings_id_idx").on(columns.listingsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [users.id],
      name: "users_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["listingsID"]],
      foreignColumns: [listings.id],
      name: "users_rels_listings_fk",
    }).onDelete("cascade"),
  ],
);

export const dealers_deals_in = pgTable(
  "dealers_deals_in",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_dealers_deals_in("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("dealers_deals_in_order_idx").on(columns.order),
    index("dealers_deals_in_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [dealers.id],
      name: "dealers_deals_in_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const dealers_verification_docs = pgTable(
  "dealers_verification_docs",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    file: integer("file_id")
      .notNull()
      .references(() => verification_documents.id, {
        onDelete: "set null",
      }),
  },
  (columns) => [
    index("dealers_verification_docs_order_idx").on(columns._order),
    index("dealers_verification_docs_parent_id_idx").on(columns._parentID),
    index("dealers_verification_docs_file_idx").on(columns.file),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [dealers.id],
      name: "dealers_verification_docs_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const dealers = pgTable(
  "dealers",
  {
    id: serial("id").primaryKey(),
    owner: integer("owner_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    businessName: varchar("business_name").notNull(),
    slug: varchar("slug").notNull(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    coverImage: integer("cover_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    description: varchar("description"),
    county: enum_dealers_county("county").notNull(),
    town: varchar("town"),
    physicalAddress: varchar("physical_address"),
    latitude: numeric("latitude", { mode: "number" }),
    longitude: numeric("longitude", { mode: "number" }),
    verificationExpiresAt: timestamp("verification_expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    verificationNote: varchar("verification_note"),
    contactPhone: varchar("contact_phone").notNull(),
    whatsappNumber: varchar("whatsapp_number"),
    verificationStatus: enum_dealers_verification_status(
      "verification_status",
    ).default("unverified"),
    subscriptionTier:
      enum_dealers_subscription_tier("subscription_tier").default("free"),
    subscriptionRenewsAt: timestamp("subscription_renews_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("dealers_owner_idx").on(columns.owner),
    uniqueIndex("dealers_slug_idx").on(columns.slug),
    index("dealers_logo_idx").on(columns.logo),
    index("dealers_cover_image_idx").on(columns.coverImage),
    index("dealers_updated_at_idx").on(columns.updatedAt),
    index("dealers_created_at_idx").on(columns.createdAt),
  ],
);

export const service_providers_services = pgTable(
  "service_providers_services",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_service_providers_services("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("service_providers_services_order_idx").on(columns.order),
    index("service_providers_services_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [service_providers.id],
      name: "service_providers_services_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const service_providers = pgTable(
  "service_providers",
  {
    id: serial("id").primaryKey(),
    owner: integer("owner_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    businessName: varchar("business_name").notNull(),
    slug: varchar("slug").notNull(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    description: varchar("description").notNull(),
    makesServiced: varchar("makes_serviced"),
    website: varchar("website"),
    contactPhone: varchar("contact_phone").notNull(),
    whatsappNumber: varchar("whatsapp_number"),
    county: varchar("county").notNull(),
    town: varchar("town"),
    physicalAddress: varchar("physical_address"),
    latitude: numeric("latitude", { mode: "number" }),
    longitude: numeric("longitude", { mode: "number" }),
    verificationStatus: enum_service_providers_verification_status(
      "verification_status",
    ).default("pending"),
    verificationExpiresAt: timestamp("verification_expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    verificationNote: varchar("verification_note"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("service_providers_owner_idx").on(columns.owner),
    uniqueIndex("service_providers_slug_idx").on(columns.slug),
    index("service_providers_logo_idx").on(columns.logo),
    index("service_providers_updated_at_idx").on(columns.updatedAt),
    index("service_providers_created_at_idx").on(columns.createdAt),
  ],
);

export const listings_images = pgTable(
  "listings_images",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
  },
  (columns) => [
    index("listings_images_order_idx").on(columns._order),
    index("listings_images_parent_id_idx").on(columns._parentID),
    index("listings_images_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [listings.id],
      name: "listings_images_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const listings_risk_reasons = pgTable(
  "listings_risk_reasons",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    reason: varchar("reason"),
  },
  (columns) => [
    index("listings_risk_reasons_order_idx").on(columns._order),
    index("listings_risk_reasons_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [listings.id],
      name: "listings_risk_reasons_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const listings = pgTable(
  "listings",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    seller: integer("seller_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    dealer: integer("dealer_id").references(() => dealers.id, {
      onDelete: "set null",
    }),
    category: enum_listings_category("category").notNull(),
    condition: enum_listings_condition("condition").notNull(),
    make: varchar("make").notNull(),
    model: varchar("model").notNull(),
    modelNumber: varchar("model_number"),
    trim: varchar("trim"),
    yearOfManufacture: numeric("year_of_manufacture", {
      mode: "number",
    }).notNull(),
    transmission: enum_listings_transmission("transmission"),
    driveConfiguration: varchar("drive_configuration"),
    fuelType: enum_listings_fuel_type("fuel_type"),
    engineCc: numeric("engine_cc", { mode: "number" }),
    mileageKm: numeric("mileage_km", { mode: "number" }),
    bodyType: enum_listings_body_type("body_type"),
    grossVehicleWeightKg: numeric("gross_vehicle_weight_kg", { mode: "number" }),
    seatingCapacity: numeric("seating_capacity", { mode: "number" }),
    color: varchar("color"),
    crspRecord: integer("crsp_record_id").references(() => crsp_schedule.id, {
      onDelete: "set null",
    }),
    crspValueKes: numeric("crsp_value_kes", { mode: "number" }),
    heavyMachineSpecs_equipmentType:
      enum_listings_heavy_machine_specs_equipment_type(
        "heavy_machine_specs_equipment_type",
      ),
    heavyMachineSpecs_powerRatingHp: numeric(
      "heavy_machine_specs_power_rating_hp",
      { mode: "number" },
    ),
    heavyMachineSpecs_operatingHours: numeric(
      "heavy_machine_specs_operating_hours",
      { mode: "number" },
    ),
    heavyMachineSpecs_capacityOrTonnage: varchar(
      "heavy_machine_specs_capacity_or_tonnage",
    ),
    heavyMachineSpecs_attachments: varchar("heavy_machine_specs_attachments"),
    sparePartDetails_partType: varchar("spare_part_details_part_type"),
    sparePartDetails_compatibleModels: varchar(
      "spare_part_details_compatible_models",
    ),
    sparePartDetails_partCondition:
      enum_listings_spare_part_details_part_condition(
        "spare_part_details_part_condition",
      ),
    dutyStatus: enum_listings_duty_status("duty_status"),
    vinOrChassis: varchar("vin_or_chassis"),
    price: numeric("price", { mode: "number" }).notNull(),
    negotiable: boolean("negotiable").default(true),
    currency: enum_listings_currency("currency").default("KES"),
    description: varchar("description").notNull(),
    videoUrl: varchar("video_url"),
    county: enum_listings_county("county").notNull(),
    town: varchar("town"),
    latitude: numeric("latitude", { mode: "number" }),
    longitude: numeric("longitude", { mode: "number" }),
    status: enum_listings_status("status").default("pending-review"),
    moderationFlag:
      enum_listings_moderation_flag("moderation_flag").default("none"),
    riskScore: numeric("risk_score", { mode: "number" }).default(0),
    moderationNote: varchar("moderation_note"),
    featured: boolean("featured").default(false),
    featuredUntil: timestamp("featured_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    views: numeric("views", { mode: "number" }).default(0),
    inquiryCount: numeric("inquiry_count", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("listings_slug_idx").on(columns.slug),
    index("listings_seller_idx").on(columns.seller),
    index("listings_dealer_idx").on(columns.dealer),
    index("listings_category_idx").on(columns.category),
    index("listings_condition_idx").on(columns.condition),
    index("listings_make_idx").on(columns.make),
    index("listings_model_idx").on(columns.model),
    index("listings_crsp_record_id_idx").on(columns.crspRecord),
    index("listings_crsp_value_kes_idx").on(columns.crspValueKes),
    index("listings_year_of_manufacture_idx").on(columns.yearOfManufacture),
    index("listings_mileage_km_idx").on(columns.mileageKm),
    index("listings_price_idx").on(columns.price),
    index("listings_status_idx").on(columns.status),
    index("listings_featured_idx").on(columns.featured),
    index("listings_updated_at_idx").on(columns.updatedAt),
    index("listings_created_at_idx").on(columns.createdAt),
  ],
);

export const reviews = pgTable(
  "reviews",
  {
    id: serial("id").primaryKey(),
    author: integer("author_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    targetType: enum_reviews_target_type("target_type").notNull(),
    targetId: varchar("target_id").notNull(),
    rating: numeric("rating", { mode: "number" }).notNull(),
    title: varchar("title").notNull(),
    body: varchar("body").notNull(),
    status: enum_reviews_status("status").default("pending"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("reviews_author_idx").on(columns.author),
    index("reviews_updated_at_idx").on(columns.updatedAt),
    index("reviews_created_at_idx").on(columns.createdAt),
  ],
);

export const reports = pgTable(
  "reports",
  {
    id: serial("id").primaryKey(),
    reporter: integer("reporter_id").references(() => users.id, {
      onDelete: "set null",
    }),
    targetType: enum_reports_target_type("target_type").notNull(),
    targetId: varchar("target_id").notNull(),
    reason: enum_reports_reason("reason").notNull(),
    details: varchar("details"),
    status: enum_reports_status("status").default("open"),
    assignedTo: integer("assigned_to_id").references(() => users.id, {
      onDelete: "set null",
    }),
    moderatorNote: varchar("moderator_note"),
    resolution: varchar("resolution"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("reports_reporter_idx").on(columns.reporter),
    index("reports_assigned_to_idx").on(columns.assignedTo),
    index("reports_updated_at_idx").on(columns.updatedAt),
    index("reports_created_at_idx").on(columns.createdAt),
  ],
);

export const contact_messages = pgTable(
  "contact_messages",
  {
    id: serial("id").primaryKey(),
    sender: integer("sender_id").references(() => users.id, {
      onDelete: "set null",
    }),
    name: varchar("name").notNull(),
    email: varchar("email"),
    phone: varchar("phone"),
    subject: varchar("subject").notNull(),
    message: varchar("message").notNull(),
    status: enum_contact_messages_status("status").default("new"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("contact_messages_sender_idx").on(columns.sender),
    index("contact_messages_updated_at_idx").on(columns.updatedAt),
    index("contact_messages_created_at_idx").on(columns.createdAt),
  ],
);

export const audit_logs = pgTable(
  "audit_logs",
  {
    id: serial("id").primaryKey(),
    actor: integer("actor_id").references(() => users.id, {
      onDelete: "set null",
    }),
    action: varchar("action").notNull(),
    targetType: varchar("target_type").notNull(),
    targetId: varchar("target_id").notNull(),
    previous: jsonb("previous"),
    next: jsonb("next"),
    note: varchar("note"),
    ip: varchar("ip"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("audit_logs_actor_idx").on(columns.actor),
    index("audit_logs_updated_at_idx").on(columns.updatedAt),
    index("audit_logs_created_at_idx").on(columns.createdAt),
  ],
);

export const verification_documents = pgTable(
  "verification_documents",
  {
    id: serial("id").primaryKey(),
    ownerType: enum_verification_documents_owner_type("owner_type").notNull(),
    ownerId: varchar("owner_id").notNull(),
    documentType:
      enum_verification_documents_document_type("document_type").notNull(),
    status: enum_verification_documents_status("status").default("pending"),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    reviewNote: varchar("review_note"),
    reviewedBy: integer("reviewed_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    reviewedAt: timestamp("reviewed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("verification_documents_reviewed_by_idx").on(columns.reviewedBy),
    index("verification_documents_updated_at_idx").on(columns.updatedAt),
    index("verification_documents_created_at_idx").on(columns.createdAt),
    uniqueIndex("verification_documents_filename_idx").on(columns.filename),
  ],
);

export const conversations = pgTable(
  "conversations",
  {
    id: serial("id").primaryKey(),
    listing: integer("listing_id").references(() => listings.id, {
      onDelete: "set null",
    }),
    lastMessageAt: timestamp("last_message_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("conversations_listing_idx").on(columns.listing),
    index("conversations_updated_at_idx").on(columns.updatedAt),
    index("conversations_created_at_idx").on(columns.createdAt),
  ],
);

export const conversations_rels = pgTable(
  "conversations_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("conversations_rels_order_idx").on(columns.order),
    index("conversations_rels_parent_idx").on(columns.parent),
    index("conversations_rels_path_idx").on(columns.path),
    index("conversations_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [conversations.id],
      name: "conversations_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "conversations_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const messages = pgTable(
  "messages",
  {
    id: serial("id").primaryKey(),
    conversation: integer("conversation_id")
      .notNull()
      .references(() => conversations.id, {
        onDelete: "set null",
      }),
    sender: integer("sender_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    body: varchar("body").notNull(),
    readAt: timestamp("read_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("messages_conversation_idx").on(columns.conversation),
    index("messages_sender_idx").on(columns.sender),
    index("messages_updated_at_idx").on(columns.updatedAt),
    index("messages_created_at_idx").on(columns.createdAt),
  ],
);

export const whatsapp_submissions = pgTable(
  "whatsapp_submissions",
  {
    id: serial("id").primaryKey(),
    fromPhone: varchar("from_phone").notNull(),
    rawText: varchar("raw_text"),
    parsed: jsonb("parsed"),
    claimedBy: integer("claimed_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    claimTokenUsedAt: timestamp("claim_token_used_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    claimExpiresAt: timestamp("claim_expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    status: enum_whatsapp_submissions_status("status").default("received"),
    onboardingStatus:
      enum_whatsapp_submissions_onboarding_status("onboarding_status").default(
        "unassigned",
      ),
    assignedTo: integer("assigned_to_id").references(() => users.id, {
      onDelete: "set null",
    }),
    followUpAt: timestamp("follow_up_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    slaDueAt: timestamp("sla_due_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    staffNotes: varchar("staff_notes"),
    dealer: integer("dealer_id").references(() => dealers.id, {
      onDelete: "set null",
    }),
    listing: integer("listing_id").references(() => listings.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("whatsapp_submissions_from_phone_idx").on(columns.fromPhone),
    index("whatsapp_submissions_claimed_by_idx").on(columns.claimedBy),
    index("whatsapp_submissions_assigned_to_idx").on(columns.assignedTo),
    index("whatsapp_submissions_dealer_idx").on(columns.dealer),
    index("whatsapp_submissions_listing_idx").on(columns.listing),
    index("whatsapp_submissions_updated_at_idx").on(columns.updatedAt),
    index("whatsapp_submissions_created_at_idx").on(columns.createdAt),
  ],
);

export const whatsapp_messages = pgTable(
  "whatsapp_messages",
  {
    id: serial("id").primaryKey(),
    direction: enum_whatsapp_messages_direction("direction").notNull(),
    toPhone: varchar("to_phone"),
    fromPhone: varchar("from_phone"),
    body: varchar("body"),
    submission: integer("submission_id").references(
      () => whatsapp_submissions.id,
      {
        onDelete: "set null",
      },
    ),
    providerMessageId: varchar("provider_message_id"),
    status: enum_whatsapp_messages_status("status").default("queued"),
    attempts: numeric("attempts", { mode: "number" }).default(0),
    lastError: varchar("last_error"),
    sentAt: timestamp("sent_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    deliveredAt: timestamp("delivered_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    readAt: timestamp("read_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("whatsapp_messages_submission_idx").on(columns.submission),
    index("whatsapp_messages_provider_message_id_idx").on(
      columns.providerMessageId,
    ),
    index("whatsapp_messages_updated_at_idx").on(columns.updatedAt),
    index("whatsapp_messages_created_at_idx").on(columns.createdAt),
  ],
);

export const whatsapp_media = pgTable(
  "whatsapp_media",
  {
    id: serial("id").primaryKey(),
    submission: integer("submission_id")
      .notNull()
      .references(() => whatsapp_submissions.id, {
        onDelete: "set null",
      }),
    providerMediaId: varchar("provider_media_id").notNull(),
    reviewStatus:
      enum_whatsapp_media_review_status("review_status").default("pending"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("whatsapp_media_submission_idx").on(columns.submission),
    index("whatsapp_media_provider_media_id_idx").on(columns.providerMediaId),
    index("whatsapp_media_updated_at_idx").on(columns.updatedAt),
    index("whatsapp_media_created_at_idx").on(columns.createdAt),
    uniqueIndex("whatsapp_media_filename_idx").on(columns.filename),
  ],
);

export const featured_orders = pgTable(
  "featured_orders",
  {
    id: serial("id").primaryKey(),
    listing: integer("listing_id")
      .notNull()
      .references(() => listings.id, {
        onDelete: "set null",
      }),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    plan: enum_featured_orders_plan("plan").notNull(),
    amount: numeric("amount", { mode: "number" }).notNull(),
    durationDays: numeric("duration_days", { mode: "number" }).notNull(),
    paymentProvider:
      enum_featured_orders_payment_provider("payment_provider").default(
        "mpesa",
      ),
    providerCheckoutId: varchar("provider_checkout_id"),
    status: enum_featured_orders_status("status").default("pending"),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("featured_orders_listing_idx").on(columns.listing),
    index("featured_orders_user_idx").on(columns.user),
    index("featured_orders_provider_checkout_id_idx").on(
      columns.providerCheckoutId,
    ),
    index("featured_orders_status_idx").on(columns.status),
    index("featured_orders_updated_at_idx").on(columns.updatedAt),
    index("featured_orders_created_at_idx").on(columns.createdAt),
  ],
);

export const inquiries = pgTable(
  "inquiries",
  {
    id: serial("id").primaryKey(),
    listing: integer("listing_id")
      .notNull()
      .references(() => listings.id, {
        onDelete: "set null",
      }),
    buyerUser: integer("buyer_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    buyerName: varchar("buyer_name"),
    buyerPhone: varchar("buyer_phone"),
    buyerEmail: varchar("buyer_email"),
    message: varchar("message"),
    channel: enum_inquiries_channel("channel").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("inquiries_listing_idx").on(columns.listing),
    index("inquiries_buyer_user_idx").on(columns.buyerUser),
    index("inquiries_updated_at_idx").on(columns.updatedAt),
    index("inquiries_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt"),
    uploadedBy: integer("uploaded_by_id").references(
      (): AnyPgColumn => users.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_full_url: varchar("sizes_full_url"),
    sizes_full_width: numeric("sizes_full_width", { mode: "number" }),
    sizes_full_height: numeric("sizes_full_height", { mode: "number" }),
    sizes_full_mimeType: varchar("sizes_full_mime_type"),
    sizes_full_filesize: numeric("sizes_full_filesize", { mode: "number" }),
    sizes_full_filename: varchar("sizes_full_filename"),
  },
  (columns) => [
    index("media_uploaded_by_idx").on(columns.uploadedBy),
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_full_sizes_full_filename_idx").on(
      columns.sizes_full_filename,
    ),
  ],
);

export const inspections_checklist = pgTable(
  "inspections_checklist",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    item: varchar("item").notNull(),
    result: enum_inspections_checklist_result("result"),
    note: varchar("note"),
  },
  (columns) => [
    index("inspections_checklist_order_idx").on(columns._order),
    index("inspections_checklist_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [inspections.id],
      name: "inspections_checklist_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const inspections = pgTable(
  "inspections",
  {
    id: serial("id").primaryKey(),
    listing: integer("listing_id")
      .notNull()
      .references(() => listings.id, {
        onDelete: "set null",
      }),
    requestedBy: integer("requested_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    status: enum_inspections_status("status").default("requested"),
    inspector: integer("inspector_id").references(() => users.id, {
      onDelete: "set null",
    }),
    inspectionDate: timestamp("inspection_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    overallResult: enum_inspections_overall_result("overall_result"),
    reportFile: integer("report_file_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("inspections_listing_idx").on(columns.listing),
    index("inspections_requested_by_idx").on(columns.requestedBy),
    index("inspections_inspector_idx").on(columns.inspector),
    index("inspections_report_file_idx").on(columns.reportFile),
    index("inspections_updated_at_idx").on(columns.updatedAt),
    index("inspections_created_at_idx").on(columns.createdAt),
  ],
);

export const phone_otps = pgTable(
  "phone_otps",
  {
    id: serial("id").primaryKey(),
    phone: varchar("phone").notNull(),
    codeHash: varchar("code_hash").notNull(),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    attempts: numeric("attempts", { mode: "number" }).default(0),
    consumed: boolean("consumed").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("phone_otps_phone_idx").on(columns.phone),
    index("phone_otps_updated_at_idx").on(columns.updatedAt),
    index("phone_otps_created_at_idx").on(columns.createdAt),
  ],
);

export const crsp_schedule = pgTable(
  "crsp_schedule",
  {
    id: serial("id").primaryKey(),
    make: varchar("make").notNull(),
    model: varchar("model").notNull(),
    modelNumber: varchar("model_number"),
    variant: varchar("variant"),
    transmission: varchar("transmission"),
    driveConfiguration: varchar("drive_configuration"),
    engineCc: numeric("engine_cc", { mode: "number" }),
    fuelType: enum_crsp_schedule_fuel_type("fuel_type"),
    bodyType: varchar("body_type"),
    gvwKg: numeric("gvw_kg", { mode: "number" }),
    seatingCapacity: numeric("seating_capacity", { mode: "number" }),
    category: enum_crsp_schedule_category("category").notNull(),
    crspValueKes: numeric("crsp_value_kes", { mode: "number" }).notNull(),
    verified: boolean("verified").default(false),
    sourceNote: varchar("source_note"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("crsp_schedule_make_idx").on(columns.make),
    index("crsp_schedule_model_idx").on(columns.model),
    index("crsp_schedule_make_model_idx").on(columns.make, columns.model),
    index("crsp_schedule_updated_at_idx").on(columns.updatedAt),
    index("crsp_schedule_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    dealersID: integer("dealers_id"),
    "service-providersID": integer("service_providers_id"),
    listingsID: integer("listings_id"),
    reviewsID: integer("reviews_id"),
    reportsID: integer("reports_id"),
    "contact-messagesID": integer("contact_messages_id"),
    "audit-logsID": integer("audit_logs_id"),
    "verification-documentsID": integer("verification_documents_id"),
    conversationsID: integer("conversations_id"),
    messagesID: integer("messages_id"),
    "whatsapp-submissionsID": integer("whatsapp_submissions_id"),
    "whatsapp-messagesID": integer("whatsapp_messages_id"),
    "whatsapp-mediaID": integer("whatsapp_media_id"),
    "featured-ordersID": integer("featured_orders_id"),
    inquiriesID: integer("inquiries_id"),
    mediaID: integer("media_id"),
    inspectionsID: integer("inspections_id"),
    "phone-otpsID": integer("phone_otps_id"),
    "crsp-scheduleID": integer("crsp_schedule_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_dealers_id_idx").on(columns.dealersID),
    index("payload_locked_documents_rels_service_providers_id_idx").on(
      columns["service-providersID"],
    ),
    index("payload_locked_documents_rels_listings_id_idx").on(
      columns.listingsID,
    ),
    index("payload_locked_documents_rels_reviews_id_idx").on(columns.reviewsID),
    index("payload_locked_documents_rels_reports_id_idx").on(columns.reportsID),
    index("payload_locked_documents_rels_contact_messages_id_idx").on(
      columns["contact-messagesID"],
    ),
    index("payload_locked_documents_rels_audit_logs_id_idx").on(
      columns["audit-logsID"],
    ),
    index("payload_locked_documents_rels_verification_documents_id_idx").on(
      columns["verification-documentsID"],
    ),
    index("payload_locked_documents_rels_conversations_id_idx").on(
      columns.conversationsID,
    ),
    index("payload_locked_documents_rels_messages_id_idx").on(
      columns.messagesID,
    ),
    index("payload_locked_documents_rels_whatsapp_submissions_id_idx").on(
      columns["whatsapp-submissionsID"],
    ),
    index("payload_locked_documents_rels_whatsapp_messages_id_idx").on(
      columns["whatsapp-messagesID"],
    ),
    index("payload_locked_documents_rels_whatsapp_media_id_idx").on(
      columns["whatsapp-mediaID"],
    ),
    index("payload_locked_documents_rels_featured_orders_id_idx").on(
      columns["featured-ordersID"],
    ),
    index("payload_locked_documents_rels_inquiries_id_idx").on(
      columns.inquiriesID,
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_inspections_id_idx").on(
      columns.inspectionsID,
    ),
    index("payload_locked_documents_rels_phone_otps_id_idx").on(
      columns["phone-otpsID"],
    ),
    index("payload_locked_documents_rels_crsp_schedule_id_idx").on(
      columns["crsp-scheduleID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["dealersID"]],
      foreignColumns: [dealers.id],
      name: "payload_locked_documents_rels_dealers_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["service-providersID"]],
      foreignColumns: [service_providers.id],
      name: "payload_locked_documents_rels_service_providers_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["listingsID"]],
      foreignColumns: [listings.id],
      name: "payload_locked_documents_rels_listings_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["reviewsID"]],
      foreignColumns: [reviews.id],
      name: "payload_locked_documents_rels_reviews_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["reportsID"]],
      foreignColumns: [reports.id],
      name: "payload_locked_documents_rels_reports_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["contact-messagesID"]],
      foreignColumns: [contact_messages.id],
      name: "payload_locked_documents_rels_contact_messages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["audit-logsID"]],
      foreignColumns: [audit_logs.id],
      name: "payload_locked_documents_rels_audit_logs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["verification-documentsID"]],
      foreignColumns: [verification_documents.id],
      name: "payload_locked_documents_rels_verification_documents_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["conversationsID"]],
      foreignColumns: [conversations.id],
      name: "payload_locked_documents_rels_conversations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["messagesID"]],
      foreignColumns: [messages.id],
      name: "payload_locked_documents_rels_messages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["whatsapp-submissionsID"]],
      foreignColumns: [whatsapp_submissions.id],
      name: "payload_locked_documents_rels_whatsapp_submissions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["whatsapp-messagesID"]],
      foreignColumns: [whatsapp_messages.id],
      name: "payload_locked_documents_rels_whatsapp_messages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["whatsapp-mediaID"]],
      foreignColumns: [whatsapp_media.id],
      name: "payload_locked_documents_rels_whatsapp_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["featured-ordersID"]],
      foreignColumns: [featured_orders.id],
      name: "payload_locked_documents_rels_featured_orders_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["inquiriesID"]],
      foreignColumns: [inquiries.id],
      name: "payload_locked_documents_rels_inquiries_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["inspectionsID"]],
      foreignColumns: [inspections.id],
      name: "payload_locked_documents_rels_inspections_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["phone-otpsID"]],
      foreignColumns: [phone_otps.id],
      name: "payload_locked_documents_rels_phone_otps_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["crsp-scheduleID"]],
      foreignColumns: [crsp_schedule.id],
      name: "payload_locked_documents_rels_crsp_schedule_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users_rels = relations(users_rels, ({ one }) => ({
  parent: one(users, {
    fields: [users_rels.parent],
    references: [users.id],
    relationName: "_rels",
  }),
  listingsID: one(listings, {
    fields: [users_rels.listingsID],
    references: [listings.id],
    relationName: "listings",
  }),
}));
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
  _rels: many(users_rels, {
    relationName: "_rels",
  }),
}));
export const relations_dealers_deals_in = relations(
  dealers_deals_in,
  ({ one }) => ({
    parent: one(dealers, {
      fields: [dealers_deals_in.parent],
      references: [dealers.id],
      relationName: "dealsIn",
    }),
  }),
);
export const relations_dealers_verification_docs = relations(
  dealers_verification_docs,
  ({ one }) => ({
    _parentID: one(dealers, {
      fields: [dealers_verification_docs._parentID],
      references: [dealers.id],
      relationName: "verificationDocs",
    }),
    file: one(verification_documents, {
      fields: [dealers_verification_docs.file],
      references: [verification_documents.id],
      relationName: "file",
    }),
  }),
);
export const relations_dealers = relations(dealers, ({ one, many }) => ({
  owner: one(users, {
    fields: [dealers.owner],
    references: [users.id],
    relationName: "owner",
  }),
  logo: one(media, {
    fields: [dealers.logo],
    references: [media.id],
    relationName: "logo",
  }),
  coverImage: one(media, {
    fields: [dealers.coverImage],
    references: [media.id],
    relationName: "coverImage",
  }),
  dealsIn: many(dealers_deals_in, {
    relationName: "dealsIn",
  }),
  verificationDocs: many(dealers_verification_docs, {
    relationName: "verificationDocs",
  }),
}));
export const relations_service_providers_services = relations(
  service_providers_services,
  ({ one }) => ({
    parent: one(service_providers, {
      fields: [service_providers_services.parent],
      references: [service_providers.id],
      relationName: "services",
    }),
  }),
);
export const relations_service_providers = relations(
  service_providers,
  ({ one, many }) => ({
    owner: one(users, {
      fields: [service_providers.owner],
      references: [users.id],
      relationName: "owner",
    }),
    logo: one(media, {
      fields: [service_providers.logo],
      references: [media.id],
      relationName: "logo",
    }),
    services: many(service_providers_services, {
      relationName: "services",
    }),
  }),
);
export const relations_listings_images = relations(
  listings_images,
  ({ one }) => ({
    _parentID: one(listings, {
      fields: [listings_images._parentID],
      references: [listings.id],
      relationName: "images",
    }),
    image: one(media, {
      fields: [listings_images.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_listings_risk_reasons = relations(
  listings_risk_reasons,
  ({ one }) => ({
    _parentID: one(listings, {
      fields: [listings_risk_reasons._parentID],
      references: [listings.id],
      relationName: "riskReasons",
    }),
  }),
);
export const relations_listings = relations(listings, ({ one, many }) => ({
  seller: one(users, {
    fields: [listings.seller],
    references: [users.id],
    relationName: "seller",
  }),
  dealer: one(dealers, {
    fields: [listings.dealer],
    references: [dealers.id],
    relationName: "dealer",
  }),
  crspRecord: one(crsp_schedule, {
    fields: [listings.crspRecord],
    references: [crsp_schedule.id],
    relationName: "crspRecord",
  }),
  images: many(listings_images, {
    relationName: "images",
  }),
  riskReasons: many(listings_risk_reasons, {
    relationName: "riskReasons",
  }),
}));
export const relations_reviews = relations(reviews, ({ one }) => ({
  author: one(users, {
    fields: [reviews.author],
    references: [users.id],
    relationName: "author",
  }),
}));
export const relations_reports = relations(reports, ({ one }) => ({
  reporter: one(users, {
    fields: [reports.reporter],
    references: [users.id],
    relationName: "reporter",
  }),
  assignedTo: one(users, {
    fields: [reports.assignedTo],
    references: [users.id],
    relationName: "assignedTo",
  }),
}));
export const relations_contact_messages = relations(
  contact_messages,
  ({ one }) => ({
    sender: one(users, {
      fields: [contact_messages.sender],
      references: [users.id],
      relationName: "sender",
    }),
  }),
);
export const relations_audit_logs = relations(audit_logs, ({ one }) => ({
  actor: one(users, {
    fields: [audit_logs.actor],
    references: [users.id],
    relationName: "actor",
  }),
}));
export const relations_verification_documents = relations(
  verification_documents,
  ({ one }) => ({
    reviewedBy: one(users, {
      fields: [verification_documents.reviewedBy],
      references: [users.id],
      relationName: "reviewedBy",
    }),
  }),
);
export const relations_conversations_rels = relations(
  conversations_rels,
  ({ one }) => ({
    parent: one(conversations, {
      fields: [conversations_rels.parent],
      references: [conversations.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [conversations_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_conversations = relations(
  conversations,
  ({ one, many }) => ({
    listing: one(listings, {
      fields: [conversations.listing],
      references: [listings.id],
      relationName: "listing",
    }),
    _rels: many(conversations_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_messages = relations(messages, ({ one }) => ({
  conversation: one(conversations, {
    fields: [messages.conversation],
    references: [conversations.id],
    relationName: "conversation",
  }),
  sender: one(users, {
    fields: [messages.sender],
    references: [users.id],
    relationName: "sender",
  }),
}));
export const relations_whatsapp_submissions = relations(
  whatsapp_submissions,
  ({ one }) => ({
    claimedBy: one(users, {
      fields: [whatsapp_submissions.claimedBy],
      references: [users.id],
      relationName: "claimedBy",
    }),
    assignedTo: one(users, {
      fields: [whatsapp_submissions.assignedTo],
      references: [users.id],
      relationName: "assignedTo",
    }),
    dealer: one(dealers, {
      fields: [whatsapp_submissions.dealer],
      references: [dealers.id],
      relationName: "dealer",
    }),
    listing: one(listings, {
      fields: [whatsapp_submissions.listing],
      references: [listings.id],
      relationName: "listing",
    }),
  }),
);
export const relations_whatsapp_messages = relations(
  whatsapp_messages,
  ({ one }) => ({
    submission: one(whatsapp_submissions, {
      fields: [whatsapp_messages.submission],
      references: [whatsapp_submissions.id],
      relationName: "submission",
    }),
  }),
);
export const relations_whatsapp_media = relations(
  whatsapp_media,
  ({ one }) => ({
    submission: one(whatsapp_submissions, {
      fields: [whatsapp_media.submission],
      references: [whatsapp_submissions.id],
      relationName: "submission",
    }),
  }),
);
export const relations_featured_orders = relations(
  featured_orders,
  ({ one }) => ({
    listing: one(listings, {
      fields: [featured_orders.listing],
      references: [listings.id],
      relationName: "listing",
    }),
    user: one(users, {
      fields: [featured_orders.user],
      references: [users.id],
      relationName: "user",
    }),
  }),
);
export const relations_inquiries = relations(inquiries, ({ one }) => ({
  listing: one(listings, {
    fields: [inquiries.listing],
    references: [listings.id],
    relationName: "listing",
  }),
  buyerUser: one(users, {
    fields: [inquiries.buyerUser],
    references: [users.id],
    relationName: "buyerUser",
  }),
}));
export const relations_media = relations(media, ({ one }) => ({
  uploadedBy: one(users, {
    fields: [media.uploadedBy],
    references: [users.id],
    relationName: "uploadedBy",
  }),
}));
export const relations_inspections_checklist = relations(
  inspections_checklist,
  ({ one }) => ({
    _parentID: one(inspections, {
      fields: [inspections_checklist._parentID],
      references: [inspections.id],
      relationName: "checklist",
    }),
  }),
);
export const relations_inspections = relations(
  inspections,
  ({ one, many }) => ({
    listing: one(listings, {
      fields: [inspections.listing],
      references: [listings.id],
      relationName: "listing",
    }),
    requestedBy: one(users, {
      fields: [inspections.requestedBy],
      references: [users.id],
      relationName: "requestedBy",
    }),
    inspector: one(users, {
      fields: [inspections.inspector],
      references: [users.id],
      relationName: "inspector",
    }),
    checklist: many(inspections_checklist, {
      relationName: "checklist",
    }),
    reportFile: one(media, {
      fields: [inspections.reportFile],
      references: [media.id],
      relationName: "reportFile",
    }),
  }),
);
export const relations_phone_otps = relations(phone_otps, () => ({}));
export const relations_crsp_schedule = relations(crsp_schedule, ({ many }) => ({
  listings: many(listings, { relationName: "crspRecord" }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    dealersID: one(dealers, {
      fields: [payload_locked_documents_rels.dealersID],
      references: [dealers.id],
      relationName: "dealers",
    }),
    "service-providersID": one(service_providers, {
      fields: [payload_locked_documents_rels["service-providersID"]],
      references: [service_providers.id],
      relationName: "service-providers",
    }),
    listingsID: one(listings, {
      fields: [payload_locked_documents_rels.listingsID],
      references: [listings.id],
      relationName: "listings",
    }),
    reviewsID: one(reviews, {
      fields: [payload_locked_documents_rels.reviewsID],
      references: [reviews.id],
      relationName: "reviews",
    }),
    reportsID: one(reports, {
      fields: [payload_locked_documents_rels.reportsID],
      references: [reports.id],
      relationName: "reports",
    }),
    "contact-messagesID": one(contact_messages, {
      fields: [payload_locked_documents_rels["contact-messagesID"]],
      references: [contact_messages.id],
      relationName: "contact-messages",
    }),
    "audit-logsID": one(audit_logs, {
      fields: [payload_locked_documents_rels["audit-logsID"]],
      references: [audit_logs.id],
      relationName: "audit-logs",
    }),
    "verification-documentsID": one(verification_documents, {
      fields: [payload_locked_documents_rels["verification-documentsID"]],
      references: [verification_documents.id],
      relationName: "verification-documents",
    }),
    conversationsID: one(conversations, {
      fields: [payload_locked_documents_rels.conversationsID],
      references: [conversations.id],
      relationName: "conversations",
    }),
    messagesID: one(messages, {
      fields: [payload_locked_documents_rels.messagesID],
      references: [messages.id],
      relationName: "messages",
    }),
    "whatsapp-submissionsID": one(whatsapp_submissions, {
      fields: [payload_locked_documents_rels["whatsapp-submissionsID"]],
      references: [whatsapp_submissions.id],
      relationName: "whatsapp-submissions",
    }),
    "whatsapp-messagesID": one(whatsapp_messages, {
      fields: [payload_locked_documents_rels["whatsapp-messagesID"]],
      references: [whatsapp_messages.id],
      relationName: "whatsapp-messages",
    }),
    "whatsapp-mediaID": one(whatsapp_media, {
      fields: [payload_locked_documents_rels["whatsapp-mediaID"]],
      references: [whatsapp_media.id],
      relationName: "whatsapp-media",
    }),
    "featured-ordersID": one(featured_orders, {
      fields: [payload_locked_documents_rels["featured-ordersID"]],
      references: [featured_orders.id],
      relationName: "featured-orders",
    }),
    inquiriesID: one(inquiries, {
      fields: [payload_locked_documents_rels.inquiriesID],
      references: [inquiries.id],
      relationName: "inquiries",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    inspectionsID: one(inspections, {
      fields: [payload_locked_documents_rels.inspectionsID],
      references: [inspections.id],
      relationName: "inspections",
    }),
    "phone-otpsID": one(phone_otps, {
      fields: [payload_locked_documents_rels["phone-otpsID"]],
      references: [phone_otps.id],
      relationName: "phone-otps",
    }),
    "crsp-scheduleID": one(crsp_schedule, {
      fields: [payload_locked_documents_rels["crsp-scheduleID"]],
      references: [crsp_schedule.id],
      relationName: "crsp-schedule",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_users_account_status: typeof enum_users_account_status;
  enum_users_role: typeof enum_users_role;
  enum_users_requested_role: typeof enum_users_requested_role;
  enum_dealers_deals_in: typeof enum_dealers_deals_in;
  enum_dealers_county: typeof enum_dealers_county;
  enum_dealers_verification_status: typeof enum_dealers_verification_status;
  enum_dealers_subscription_tier: typeof enum_dealers_subscription_tier;
  enum_service_providers_services: typeof enum_service_providers_services;
  enum_service_providers_verification_status: typeof enum_service_providers_verification_status;
  enum_listings_category: typeof enum_listings_category;
  enum_listings_condition: typeof enum_listings_condition;
  enum_listings_transmission: typeof enum_listings_transmission;
  enum_listings_fuel_type: typeof enum_listings_fuel_type;
  enum_listings_body_type: typeof enum_listings_body_type;
  enum_listings_heavy_machine_specs_equipment_type: typeof enum_listings_heavy_machine_specs_equipment_type;
  enum_listings_spare_part_details_part_condition: typeof enum_listings_spare_part_details_part_condition;
  enum_listings_duty_status: typeof enum_listings_duty_status;
  enum_listings_currency: typeof enum_listings_currency;
  enum_listings_county: typeof enum_listings_county;
  enum_listings_status: typeof enum_listings_status;
  enum_listings_moderation_flag: typeof enum_listings_moderation_flag;
  enum_reviews_target_type: typeof enum_reviews_target_type;
  enum_reviews_status: typeof enum_reviews_status;
  enum_reports_target_type: typeof enum_reports_target_type;
  enum_reports_reason: typeof enum_reports_reason;
  enum_reports_status: typeof enum_reports_status;
  enum_contact_messages_status: typeof enum_contact_messages_status;
  enum_verification_documents_owner_type: typeof enum_verification_documents_owner_type;
  enum_verification_documents_document_type: typeof enum_verification_documents_document_type;
  enum_verification_documents_status: typeof enum_verification_documents_status;
  enum_whatsapp_submissions_status: typeof enum_whatsapp_submissions_status;
  enum_whatsapp_submissions_onboarding_status: typeof enum_whatsapp_submissions_onboarding_status;
  enum_whatsapp_messages_direction: typeof enum_whatsapp_messages_direction;
  enum_whatsapp_messages_status: typeof enum_whatsapp_messages_status;
  enum_whatsapp_media_review_status: typeof enum_whatsapp_media_review_status;
  enum_featured_orders_plan: typeof enum_featured_orders_plan;
  enum_featured_orders_payment_provider: typeof enum_featured_orders_payment_provider;
  enum_featured_orders_status: typeof enum_featured_orders_status;
  enum_inquiries_channel: typeof enum_inquiries_channel;
  enum_inspections_checklist_result: typeof enum_inspections_checklist_result;
  enum_inspections_status: typeof enum_inspections_status;
  enum_inspections_overall_result: typeof enum_inspections_overall_result;
  enum_crsp_schedule_fuel_type: typeof enum_crsp_schedule_fuel_type;
  enum_crsp_schedule_category: typeof enum_crsp_schedule_category;
  users_sessions: typeof users_sessions;
  users: typeof users;
  users_rels: typeof users_rels;
  dealers_deals_in: typeof dealers_deals_in;
  dealers_verification_docs: typeof dealers_verification_docs;
  dealers: typeof dealers;
  service_providers_services: typeof service_providers_services;
  service_providers: typeof service_providers;
  listings_images: typeof listings_images;
  listings_risk_reasons: typeof listings_risk_reasons;
  listings: typeof listings;
  reviews: typeof reviews;
  reports: typeof reports;
  contact_messages: typeof contact_messages;
  audit_logs: typeof audit_logs;
  verification_documents: typeof verification_documents;
  conversations: typeof conversations;
  conversations_rels: typeof conversations_rels;
  messages: typeof messages;
  whatsapp_submissions: typeof whatsapp_submissions;
  whatsapp_messages: typeof whatsapp_messages;
  whatsapp_media: typeof whatsapp_media;
  featured_orders: typeof featured_orders;
  inquiries: typeof inquiries;
  media: typeof media;
  inspections_checklist: typeof inspections_checklist;
  inspections: typeof inspections;
  phone_otps: typeof phone_otps;
  crsp_schedule: typeof crsp_schedule;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users_rels: typeof relations_users_rels;
  relations_users: typeof relations_users;
  relations_dealers_deals_in: typeof relations_dealers_deals_in;
  relations_dealers_verification_docs: typeof relations_dealers_verification_docs;
  relations_dealers: typeof relations_dealers;
  relations_service_providers_services: typeof relations_service_providers_services;
  relations_service_providers: typeof relations_service_providers;
  relations_listings_images: typeof relations_listings_images;
  relations_listings_risk_reasons: typeof relations_listings_risk_reasons;
  relations_listings: typeof relations_listings;
  relations_reviews: typeof relations_reviews;
  relations_reports: typeof relations_reports;
  relations_contact_messages: typeof relations_contact_messages;
  relations_audit_logs: typeof relations_audit_logs;
  relations_verification_documents: typeof relations_verification_documents;
  relations_conversations_rels: typeof relations_conversations_rels;
  relations_conversations: typeof relations_conversations;
  relations_messages: typeof relations_messages;
  relations_whatsapp_submissions: typeof relations_whatsapp_submissions;
  relations_whatsapp_messages: typeof relations_whatsapp_messages;
  relations_whatsapp_media: typeof relations_whatsapp_media;
  relations_featured_orders: typeof relations_featured_orders;
  relations_inquiries: typeof relations_inquiries;
  relations_media: typeof relations_media;
  relations_inspections_checklist: typeof relations_inspections_checklist;
  relations_inspections: typeof relations_inspections;
  relations_phone_otps: typeof relations_phone_otps;
  relations_crsp_schedule: typeof relations_crsp_schedule;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
